config/routes.rb
Rails.application.routes.draw do
    get 'tops/main'
    post 'tops/login'
    root 'tops#main'
    get 'tops/logout'
    resources :users, only: [:index, :new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
    def main
        if session[:login_uid]
            render 'main'
        else
            render 'login'
        end
    end
    
    def login
        if User.find_by(uid: params[:uid],pass: params[:pass])
            session[:login_uid] = params[:uid]
            redirect_to tops_main_path
        else
            render 'error'
        end
    end
    def logout
        session.delete(:login_uid)
        redirect_to tops_main_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SW10</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tops/error.html.erb
ログイン失敗！
<%= link_to '戻る',root_path %>

app/views/tops/login.html.erb
<%= form_tag '/tops/login',method: :post do %>
<%= label_tag :uid, 'ユーザーID' %>
<%= text_field_tag :uid %>
<%= label_tag :pass, 'パスワード' %>
<%= password_field_tag :pass %>
<%= submit_tag '登録 '%>
<% end %>

app/views/tops/main.html.erb
ログイン中です
<%= link_to 'ログアウト', tops_logout_path %>